language: node_js
node_js:
- '6'
- node
deploy:
  provider: npm
  email: cosmosgenius@gmail.com
  api_key:
    secure: HCn9ySDxARh8M8rrF608e+bkk+buCK2kYB5BwB7pj6+5zDGhA5ZoUdKRzepIRJqp9IET6E6LA3deW0/5fJ1JFYVOVWNGjW/i7QumspnYb/gP5TZW8pwgrl1admfZk3uZb4n5mYX/xB0FWkX+G2DIUFja6YUSXkbC+g9GTrt+Yvg=
  on:
    tags: true
    repo: cosmosgenius/jsonparser
    branch: master
after_success:
- bash <(curl -s https://codecov.io/bash)
